

(function() {
	//disabled confirm exit dialog
	window.onbeforeunload = false;
	//window.alert("s");
var json = {"items": [
{"emoji":":--1:", "icon":"👍🏼", "class":"emojiordered0735"},
{"emoji":":-1:", "icon":"👎🏼", "class":"emojiordered0741"},
{"emoji":":100:", "icon":"💯", "class":"emojiordered0979"},
{"emoji":":1234:", "icon":"🔢", "class":"emojiordered1090"},
{"emoji":":8ball:", "icon":"🎱", "class":"emojiordered0546"},
{"emoji":":a:", "icon":"🅰", "class":"emojiordered0151"},
{"emoji":":ab:", "icon":"🆎", "class":"emojiordered0155"},
{"emoji":":abc:", "icon":"🔤", "class":"emojiordered1092"},
{"emoji":":abcd:", "icon":"🔡", "class":"emojiordered1089"},
{"emoji":":accept:", "icon":"🉑", "class":"emojiordered0394"},
{"emoji":":aerial_tramway:", "icon":"🚡", "class":"emojiordered1302"},
{"emoji":":airplane:", "icon":"✈", "class":"emojiordered0094"},
{"emoji":":alarm_clock:", "icon":"⏰", "class":"emojiordered0032"},
{"emoji":":alien:", "icon":"👽", "class":"emojiordered0890"},
{"emoji":":ambulance:", "icon":"🚑", "class":"emojiordered1286"},
{"emoji":":anger:", "icon":"💢", "class":"emojiordered0961"},
{"emoji":":angry:", "icon":"😠", "class":"emojiordered1185"},
{"emoji":":anguished:", "icon":"😧", "class":"emojiordered1192"},
{"emoji":":ant:", "icon":"🐜", "class":"emojiordered0641"},
{"emoji":":apple:", "icon":"🍎", "class":"emojiordered0457"},
{"emoji":":aquarius:", "icon":"♒", "class":"emojiordered0066"},
{"emoji":":aries:", "icon":"♈", "class":"emojiordered0056"},
{"emoji":":arrow_backward:", "icon":"◀", "class":"emojiordered0038"},
{"emoji":":arrow_double_down:", "icon":"⏬", "class":"emojiordered0031"},
{"emoji":":arrow_double_up:", "icon":"⏫", "class":"emojiordered0030"},
{"emoji":":arrow_down:", "icon":"⬇", "class":"emojiordered0140"},
{"emoji":":arrow_down_small:", "icon":"🔽", "class":"emojiordered1117"},
{"emoji":":arrow_forward:", "icon":"▶", "class":"emojiordered0037"},
{"emoji":":arrow_heading_down:", "icon":"⤵", "class":"emojiordered0137"},
{"emoji":":arrow_heading_up:", "icon":"⤴", "class":"emojiordered0136"},
{"emoji":":arrow_left:", "icon":"⬅", "class":"emojiordered0138"},
{"emoji":":arrow_lower_left:", "icon":"↙", "class":"emojiordered0023"},
{"emoji":":arrow_lower_right:", "icon":"↘", "class":"emojiordered0022"},
{"emoji":":arrow_right:", "icon":"➡", "class":"emojiordered0133"},
{"emoji":":arrow_right_hook:", "icon":"↪", "class":"emojiordered0025"},
{"emoji":":arrow_up:", "icon":"⬆", "class":"emojiordered0139"},
{"emoji":":arrow_up_down:", "icon":"↕", "class":"emojiordered0019"},
{"emoji":":arrow_up_small:", "icon":"🔼", "class":"emojiordered1116"},
{"emoji":":arrow_upper_left:", "icon":"↖", "class":"emojiordered0020"},
{"emoji":":arrow_upper_right:", "icon":"↗", "class":"emojiordered0021"},
{"emoji":":arrows_clockwise:", "icon":"🔃", "class":"emojiordered1059"},
{"emoji":":arrows_counterclockwise:", "icon":"🔄", "class":"emojiordered1060"},
{"emoji":":art:", "icon":"🎨", "class":"emojiordered0537"},
{"emoji":":articulated_lorry:", "icon":"🚛", "class":"emojiordered1296"},
{"emoji":":astonished:", "icon":"😲", "class":"emojiordered1203"},
{"emoji":":atm:", "icon":"🏧", "class":"emojiordered0598"},
{"emoji":":b:", "icon":"🅱", "class":"emojiordered0152"},
{"emoji":":baby_bottle:", "icon":"🍼", "class":"emojiordered0503"},
{"emoji":":baby_chick:", "icon":"🐤", "class":"emojiordered0649"},
{"emoji":":baby_symbol:", "icon":"🚼", "class":"emojiordered1349"},
{"emoji":":back:", "icon":"🔙", "class":"emojiordered1081"},
{"emoji":":baggage_claim:", "icon":"🛄", "class":"emojiordered1362"},
{"emoji":":balloon:", "icon":"🎈", "class":"emojiordered0517"},
{"emoji":":ballot_box_with_check:", "icon":"☑", "class":"emojiordered0046"},
{"emoji":":bamboo:", "icon":"🎍", "class":"emojiordered0522"},
{"emoji":":banana:", "icon":"🍌", "class":"emojiordered0455"},
{"emoji":":bank:", "icon":"🏦", "class":"emojiordered0597"},
{"emoji":":bar_chart:", "icon":"📊", "class":"emojiordered1006"},
{"emoji":":barber:", "icon":"💈", "class":"emojiordered0931"},
{"emoji":":baseball:", "icon":"⚾", "class":"emojiordered0081"},
{"emoji":":basketball:", "icon":"🏀", "class":"emojiordered0561"},
{"emoji":":bathtub:", "icon":"🛁", "class":"emojiordered1359"},
{"emoji":":battery:", "icon":"🔋", "class":"emojiordered1067"},
{"emoji":":bear:", "icon":"🐻", "class":"emojiordered0672"},
{"emoji":":beer:", "icon":"🍺", "class":"emojiordered0501"},
{"emoji":":beers:", "icon":"🍻", "class":"emojiordered0502"},
{"emoji":":beetle:", "icon":"🐞", "class":"emojiordered0643"},
{"emoji":":beginner:", "icon":"🔰", "class":"emojiordered1104"},
{"emoji":":bell:", "icon":"🔔", "class":"emojiordered1076"},
{"emoji":":bento:", "icon":"🍱", "class":"emojiordered0492"},
{"emoji":":bike:", "icon":"🚲", "class":"emojiordered1324"},
{"emoji":":bikini:", "icon":"👙", "class":"emojiordered0765"},
{"emoji":":bird:", "icon":"🐦", "class":"emojiordered0651"},
{"emoji":":birthday:", "icon":"🎂", "class":"emojiordered0506"},
{"emoji":":black_circle:", "icon":"⚫", "class":"emojiordered0079"},
{"emoji":":black_joker:", "icon":"🃏", "class":"emojiordered0150"},
{"emoji":":black_large_square:", "icon":"⬛", "class":"emojiordered0141"},
{"emoji":":black_medium_small_square:", "icon":"◾", "class":"emojiordered0042"},
{"emoji":":black_medium_square:", "icon":"◼", "class":"emojiordered0040"},
{"emoji":":black_nib:", "icon":"✒", "class":"emojiordered0115"},
{"emoji":":black_small_square:", "icon":"▪", "class":"emojiordered0035"},
{"emoji":":black_square_button:", "icon":"🔲", "class":"emojiordered1106"},
{"emoji":":blossom:", "icon":"🌼", "class":"emojiordered0439"},
{"emoji":":blowfish:", "icon":"🐡", "class":"emojiordered0646"},
{"emoji":":blue_book:", "icon":"📘", "class":"emojiordered1020"},
{"emoji":":blue_car:", "icon":"🚙", "class":"emojiordered1294"},
{"emoji":":blue_heart:", "icon":"💙", "class":"emojiordered0952"},
{"emoji":":blush:", "icon":"😊", "class":"emojiordered1163"},
{"emoji":":boar:", "icon":"🐗", "class":"emojiordered0636"},
{"emoji":":boat:", "icon":"⛵", "class":"emojiordered0089"},
{"emoji":":bomb:", "icon":"💣", "class":"emojiordered0962"},
{"emoji":":book:", "icon":"📖", "class":"emojiordered1018"},
{"emoji":":bookmark:", "icon":"🔖", "class":"emojiordered1078"},
{"emoji":":bookmark_tabs:", "icon":"📑", "class":"emojiordered1013"},
{"emoji":":books:", "icon":"📚", "class":"emojiordered1022"},
{"emoji":":boom:", "icon":"💥", "class":"emojiordered0964"},
{"emoji":":boot:", "icon":"👢", "class":"emojiordered0774"},
{"emoji":":bouquet:", "icon":"💐", "class":"emojiordered0941"},
{"emoji":":bowling:", "icon":"🎳", "class":"emojiordered0548"},
{"emoji":":bread:", "icon":"🍞", "class":"emojiordered0473"},
{"emoji":":bridge_at_night:", "icon":"🌉", "class":"emojiordered0404"},
{"emoji":":briefcase:", "icon":"💼", "class":"emojiordered0992"},
{"emoji":":broken_heart2:", "icon":"💔", "class":"emojiordered0947"},
{"emoji":":broken_heart:", "icon":"💔", "class":"emojiordered0947"},
{"emoji":":bug:", "icon":"🐛", "class":"emojiordered0640"},
{"emoji":":bulb:", "icon":"💡", "class":"emojiordered0960"},
{"emoji":":bullettrain_front:", "icon":"🚆", "class":"emojiordered1275"},
{"emoji":":bullettrain_side2:", "icon":"🚄", "class":"emojiordered1273"},
{"emoji":":bullettrain_side:", "icon":"🚅", "class":"emojiordered1274"},
{"emoji":":bus:", "icon":"🚌", "class":"emojiordered1281"},
{"emoji":":busstop:", "icon":"🚏", "class":"emojiordered1284"},
{"emoji":":bust_in_silhouette:", "icon":"👤", "class":"emojiordered0776"},
{"emoji":":busts_in_silhouette:", "icon":"👥", "class":"emojiordered0777"},
{"emoji":":cactus:", "icon":"🌵", "class":"emojiordered0433"},
{"emoji":":cake:", "icon":"🍰", "class":"emojiordered0491"},
{"emoji":":calendar:", "icon":"📆", "class":"emojiordered1002"},
{"emoji":":calling:", "icon":"📲", "class":"emojiordered1046"},
{"emoji":":camel:", "icon":"🐫", "class":"emojiordered0656"},
{"emoji":":camera:", "icon":"📷", "class":"emojiordered1051"},
{"emoji":":cancer:", "icon":"♋", "class":"emojiordered0059"},
{"emoji":":candy:", "icon":"🍬", "class":"emojiordered0487"},
{"emoji":":capital_abcd:", "icon":"🔠", "class":"emojiordered1088"},
{"emoji":":capricorn:", "icon":"♑", "class":"emojiordered0065"},
{"emoji":":car:", "icon":"🚗", "class":"emojiordered1292"},
{"emoji":":card_index:", "icon":"📇", "class":"emojiordered1003"},
{"emoji":":carousel_horse:", "icon":"🎠", "class":"emojiordered0529"},
{"emoji":":cat2:", "icon":"🐈", "class":"emojiordered0621"},
{"emoji":":cat:", "icon":"🐱", "class":"emojiordered0662"},
{"emoji":":cd:", "icon":"💿", "class":"emojiordered0995"},
{"emoji":":chart:", "icon":"💹", "class":"emojiordered0989"},
{"emoji":":chart_with_downwards_trend:", "icon":"📉", "class":"emojiordered1005"},
{"emoji":":chart_with_upwards_trend:", "icon":"📈", "class":"emojiordered1004"},
{"emoji":":checkered_flag:", "icon":"🏁", "class":"emojiordered0562"},
{"emoji":":cherries:", "icon":"🍒", "class":"emojiordered0461"},
{"emoji":":cherry_blossom:", "icon":"🌸", "class":"emojiordered0435"},
{"emoji":":chestnut:", "icon":"🌰", "class":"emojiordered0428"},
{"emoji":":chicken:", "icon":"🐔", "class":"emojiordered0633"},
{"emoji":":children_crossing:", "icon":"🚸", "class":"emojiordered1345"},
{"emoji":":chocolate_bar:", "icon":"🍫", "class":"emojiordered0486"},
{"emoji":":church:", "icon":"⛪", "class":"emojiordered0086"},
{"emoji":":cinema:", "icon":"🎦", "class":"emojiordered0535"},
{"emoji":":circus_tent:", "icon":"🎪", "class":"emojiordered0539"},
{"emoji":":city_night:", "icon":"🌃", "class":"emojiordered0398"},
{"emoji":":city_sunrise:", "icon":"🌇", "class":"emojiordered0402"},
{"emoji":":city_sunset:", "icon":"🌆", "class":"emojiordered0401"},
{"emoji":":cl:", "icon":"🆑", "class":"emojiordered0156"},
{"emoji":":clapper:", "icon":"🎬", "class":"emojiordered0541"},
{"emoji":":clipboard:", "icon":"📋", "class":"emojiordered1007"},
{"emoji":":clock1030:", "icon":"🕥", "class":"emojiordered1139"},
{"emoji":":clock10:", "icon":"🕙", "class":"emojiordered1127"},
{"emoji":":clock1130:", "icon":"🕦", "class":"emojiordered1140"},
{"emoji":":clock11:", "icon":"🕚", "class":"emojiordered1128"},
{"emoji":":clock1230:", "icon":"🕧", "class":"emojiordered1141"},
{"emoji":":clock12:", "icon":"🕛", "class":"emojiordered1129"},
{"emoji":":clock130:", "icon":"🕜", "class":"emojiordered1130"},
{"emoji":":clock1:", "icon":"🕐", "class":"emojiordered1118"},
{"emoji":":clock230:", "icon":"🕝", "class":"emojiordered1131"},
{"emoji":":clock2:", "icon":"🕑", "class":"emojiordered1119"},
{"emoji":":clock330:", "icon":"🕞", "class":"emojiordered1132"},
{"emoji":":clock3:", "icon":"🕒", "class":"emojiordered1120"},
{"emoji":":clock430:", "icon":"🕟", "class":"emojiordered1133"},
{"emoji":":clock4:", "icon":"🕓", "class":"emojiordered1121"},
{"emoji":":clock530:", "icon":"🕠", "class":"emojiordered1134"},
{"emoji":":clock5:", "icon":"🕔", "class":"emojiordered1122"},
{"emoji":":clock630:", "icon":"🕡", "class":"emojiordered1135"},
{"emoji":":clock6:", "icon":"🕕", "class":"emojiordered1123"},
{"emoji":":clock730:", "icon":"🕢", "class":"emojiordered1136"},
{"emoji":":clock7:", "icon":"🕖", "class":"emojiordered1124"},
{"emoji":":clock830:", "icon":"🕣", "class":"emojiordered1137"},
{"emoji":":clock8:", "icon":"🕗", "class":"emojiordered1125"},
{"emoji":":clock930:", "icon":"🕤", "class":"emojiordered1138"},
{"emoji":":clock9:", "icon":"🕘", "class":"emojiordered1126"},
{"emoji":":closed_book:", "icon":"📕", "class":"emojiordered1017"},
{"emoji":":closed_lock_with_key:", "icon":"🔐", "class":"emojiordered1072"},
{"emoji":":closed_umbrella:", "icon":"🌂", "class":"emojiordered0397"},
{"emoji":":cloud:", "icon":"☁", "class":"emojiordered0044"},
{"emoji":":clubs:", "icon":"♣", "class":"emojiordered0069"},
{"emoji":":cn:", "icon":"🇨🇳", "class":"emojiordered0204"},
{"emoji":":cocktail:", "icon":"🍸", "class":"emojiordered0499"},
{"emoji":":coffee:", "icon":"☕", "class":"emojiordered0048"},
{"emoji":":cold_sweat:", "icon":"😰", "class":"emojiordered1201"},
{"emoji":":computer:", "icon":"💻", "class":"emojiordered0991"},
{"emoji":":confetti_ball:", "icon":"🎊", "class":"emojiordered0519"},
{"emoji":":confounded:", "icon":"😖", "class":"emojiordered1175"},
{"emoji":":confused:", "icon":"😕", "class":"emojiordered1174"},
{"emoji":":congratulations:", "icon":"㊗", "class":"emojiordered0147"},
{"emoji":":construction:", "icon":"🚧", "class":"emojiordered1313"},
{"emoji":":convenience_store:", "icon":"🏪", "class":"emojiordered0601"},
{"emoji":":cookie:", "icon":"🍪", "class":"emojiordered0485"},
{"emoji":":cool:", "icon":"🆒", "class":"emojiordered0157"},
{"emoji":":copyright:", "icon":"©", "class":"emojiordered0012"},
{"emoji":":corn:", "icon":"🌽", "class":"emojiordered0440"},
{"emoji":":couple_with_heart:", "icon":"💑", "class":"emojiordered0942"},
{"emoji":":couplekiss:", "icon":"💏", "class":"emojiordered0938"},
{"emoji":":cow2:", "icon":"🐄", "class":"emojiordered0617"},
{"emoji":":cow:", "icon":"🐮", "class":"emojiordered0659"},
{"emoji":":credit_card:", "icon":"💳", "class":"emojiordered0983"},
{"emoji":":crescent_moon:", "icon":"🌙", "class":"emojiordered0420"},
{"emoji":":crocodile:", "icon":"🐊", "class":"emojiordered0623"},
{"emoji":":crossed_flags:", "icon":"🎌", "class":"emojiordered0521"},
{"emoji":":crown:", "icon":"👑", "class":"emojiordered0757"},
{"emoji":":cry:", "icon":"😢", "class":"emojiordered1187"},
{"emoji":":crying_cat_face:", "icon":"😿", "class":"emojiordered1216"},
{"emoji":":crystal_ball:", "icon":"🔮", "class":"emojiordered1102"},
{"emoji":":cupid:", "icon":"💘", "class":"emojiordered0951"},
{"emoji":":curly_loop:", "icon":"➰", "class":"emojiordered0134"},
{"emoji":":currency_exchange:", "icon":"💱", "class":"emojiordered0981"},
{"emoji":":curry:", "icon":"🍛", "class":"emojiordered0470"},
{"emoji":":custard:", "icon":"🍮", "class":"emojiordered0489"},
{"emoji":":customs:", "icon":"🛃", "class":"emojiordered1361"},
{"emoji":":cyclone:", "icon":"🌀", "class":"emojiordered0395"},
{"emoji":":dancers:", "icon":"👯", "class":"emojiordered0826"},
{"emoji":":dango:", "icon":"🍡", "class":"emojiordered0476"},
{"emoji":":dart:", "icon":"🎯", "class":"emojiordered0544"},
{"emoji":":dash:", "icon":"💨", "class":"emojiordered0967"},
{"emoji":":date:", "icon":"📅", "class":"emojiordered1001"},
{"emoji":":de:", "icon":"🇩🇪", "class":"emojiordered0215"},
{"emoji":":deciduous_tree:", "icon":"🌳", "class":"emojiordered0431"},
{"emoji":":department_store:", "icon":"🏬", "class":"emojiordered0603"},
{"emoji":":diamond_shape_with_a_dot_inside:", "icon":"💠", "class":"emojiordered0959"},
{"emoji":":diamonds:", "icon":"♦", "class":"emojiordered0071"},
{"emoji":":disappointed:", "icon":"😞", "class":"emojiordered1183"},
{"emoji":":disappointed_relieved:", "icon":"😥", "class":"emojiordered1190"},
{"emoji":":dizzy:", "icon":"💫", "class":"emojiordered0975"},
{"emoji":":dizzy_face:", "icon":"😵", "class":"emojiordered1206"},
{"emoji":":do_not_litter:", "icon":"🚯", "class":"emojiordered1321"},
{"emoji":":dog2:", "icon":"🐕", "class":"emojiordered0634"},
{"emoji":":dog:", "icon":"🐶", "class":"emojiordered0667"},
{"emoji":":dollar:", "icon":"💵", "class":"emojiordered0985"},
{"emoji":":dolls:", "icon":"🎎", "class":"emojiordered0523"},
{"emoji":":dolphin:", "icon":"🐬", "class":"emojiordered0657"},
{"emoji":":door:", "icon":"🚪", "class":"emojiordered1316"},
{"emoji":":doughnut:", "icon":"🍩", "class":"emojiordered0484"},
{"emoji":":dragon:", "icon":"🐉", "class":"emojiordered0622"},
{"emoji":":dragon_face:", "icon":"🐲", "class":"emojiordered0663"},
{"emoji":":dress:", "icon":"👗", "class":"emojiordered0763"},
{"emoji":":dromedary_camel:", "icon":"🐪", "class":"emojiordered0655"},
{"emoji":":droplet:", "icon":"💧", "class":"emojiordered0966"},
{"emoji":":dvd:", "icon":"📀", "class":"emojiordered0996"},
{"emoji":":e-mail:", "icon":"📧", "class":"emojiordered1035"},
{"emoji":":ear_of_rice:", "icon":"🌾", "class":"emojiordered0441"},
{"emoji":":earth_africa:", "icon":"🌍", "class":"emojiordered0408"},
{"emoji":":earth_americas:", "icon":"🌎", "class":"emojiordered0409"},
{"emoji":":earth_asia:", "icon":"🌏", "class":"emojiordered0410"},
{"emoji":":egg:", "icon":"🍳", "class":"emojiordered0494"},
{"emoji":":eggplant:", "icon":"🍆", "class":"emojiordered0449"},
{"emoji":":eight:", "icon":"8⃣", "class":"emojiordered0010"},
{"emoji":":eight_pointed_black_star:", "icon":"✴", "class":"emojiordered0120"},
{"emoji":":eight_spoked_asterisk:", "icon":"✳", "class":"emojiordered0119"},
{"emoji":":electric_plug:", "icon":"🔌", "class":"emojiordered1068"},
{"emoji":":elephant:", "icon":"🐘", "class":"emojiordered0637"},
{"emoji":":email:", "icon":"✉", "class":"emojiordered0095"},
{"emoji":":end:", "icon":"🔚", "class":"emojiordered1082"},
{"emoji":":envelope:", "icon":"📨", "class":"emojiordered1036"},
{"emoji":":es:", "icon":"🇪🇸", "class":"emojiordered0222"},
{"emoji":":euro:", "icon":"💶", "class":"emojiordered0986"},
{"emoji":":european_castle:", "icon":"🏰", "class":"emojiordered0607"},
{"emoji":":european_post_office:", "icon":"🏤", "class":"emojiordered0595"},
{"emoji":":evergreen_tree:", "icon":"🌲", "class":"emojiordered0430"},
{"emoji":":exclamation:", "icon":"❗", "class":"emojiordered0128"},
{"emoji":":expressionless:", "icon":"😑", "class":"emojiordered1170"},
{"emoji":":eyeglasses:", "icon":"👓", "class":"emojiordered0759"},
{"emoji":":factory:", "icon":"🏭", "class":"emojiordered0604"},
{"emoji":":fallen_leaf:", "icon":"🍂", "class":"emojiordered0445"},
{"emoji":":family:", "icon":"👪", "class":"emojiordered0802"},
{"emoji":":fast_forward:", "icon":"⏩", "class":"emojiordered0028"},
{"emoji":":fax:", "icon":"📠", "class":"emojiordered1028"},
{"emoji":":fearful:", "icon":"😨", "class":"emojiordered1193"},
{"emoji":":feet:", "icon":"👣", "class":"emojiordered0775"},
{"emoji":":ferris_wheel:", "icon":"🎡", "class":"emojiordered0530"},
{"emoji":":file_folder:", "icon":"📁", "class":"emojiordered0997"},
{"emoji":":fire:", "icon":"🔥", "class":"emojiordered1093"},
{"emoji":":fire_engine:", "icon":"🚒", "class":"emojiordered1287"},
{"emoji":":fireworks:", "icon":"🎆", "class":"emojiordered0515"},
{"emoji":":first_quarter_moon:", "icon":"🌓", "class":"emojiordered0414"},
{"emoji":":first_quarter_moon_with_face:", "icon":"🌛", "class":"emojiordered0422"},
{"emoji":":fish:", "icon":"🐟", "class":"emojiordered0644"},
{"emoji":":fish_cake:", "icon":"🍥", "class":"emojiordered0480"},
{"emoji":":fishing_pole_and_fish:", "icon":"🎣", "class":"emojiordered0532"},
{"emoji":":five:", "icon":"5⃣", "class":"emojiordered0007"},
{"emoji":":flag-ae:", "icon":"🇦🇪", "class":"emojiordered0174"},
{"emoji":":flag-ar:", "icon":"🇦🇷", "class":"emojiordered0179"},
{"emoji":":flag-at:", "icon":"🇦🇹", "class":"emojiordered0173"},
{"emoji":":flag-au:", "icon":"🇦🇺", "class":"emojiordered0167"},
{"emoji":":flag-ba:", "icon":"🇧🇦", "class":"emojiordered0195"},
{"emoji":":flag-be:", "icon":"🇧🇪", "class":"emojiordered0189"},
{"emoji":":flag-br:", "icon":"🇧🇷", "class":"emojiordered0181"},
{"emoji":":flag-ca:", "icon":"🇨🇦", "class":"emojiordered0210"},
{"emoji":":flag-ch:", "icon":"🇨🇭", "class":"emojiordered0214"},
{"emoji":":flag-ci:", "icon":"🇨🇮", "class":"emojiordered0213"},
{"emoji":":flag-cl:", "icon":"🇨🇱", "class":"emojiordered0206"},
{"emoji":":flag-cm:", "icon":"🇨🇲", "class":"emojiordered0203"},
{"emoji":":flag-cn:", "icon":"🇨🇳", "class":"emojiordered0204"},
{"emoji":":flag-co:", "icon":"🇨🇴", "class":"emojiordered0208"},
{"emoji":":flag-cr:", "icon":"🇨🇷", "class":"emojiordered0207"},
{"emoji":":flag-de:", "icon":"🇩🇪", "class":"emojiordered0215"},
{"emoji":":flag-dz:", "icon":"🇩🇿", "class":"emojiordered0220"},
{"emoji":":flag-ec:", "icon":"🇪🇨", "class":"emojiordered0226"},
{"emoji":":flag-eg:", "icon":"🇪🇬", "class":"emojiordered0224"},
{"emoji":":flag-en:", "icon":"🇽🇪", "class":"emojiordered1365"},
{"emoji":":flag-es:", "icon":"🇪🇸", "class":"emojiordered0222"},
{"emoji":":flag-fr:", "icon":"🇫🇷", "class":"emojiordered0228"},
{"emoji":":flag-gb:", "icon":"🇬🇧", "class":"emojiordered0246"},
{"emoji":":flag-gh:", "icon":"🇬🇭", "class":"emojiordered0241"},
{"emoji":":flag-gr:", "icon":"🇬🇷", "class":"emojiordered0235"},
{"emoji":":flag-hk:", "icon":"🇭🇰", "class":"emojiordered0250"},
{"emoji":":flag-hn:", "icon":"🇭🇳", "class":"emojiordered0249"},
{"emoji":":flag-hr:", "icon":"🇭🇷", "class":"emojiordered0248"},
{"emoji":":flag-id:", "icon":"🇮🇩", "class":"emojiordered0253"},
{"emoji":":flag-il:", "icon":"🇮🇱", "class":"emojiordered0257"},
{"emoji":":flag-in:", "icon":"🇮🇳", "class":"emojiordered0256"},
{"emoji":":flag-ir:", "icon":"🇮🇷", "class":"emojiordered0254"},
{"emoji":":flag-it:", "icon":"🇮🇹", "class":"emojiordered0258"},
{"emoji":":flag-jo:", "icon":"🇯🇴", "class":"emojiordered0260"},
{"emoji":":flag-jp:", "icon":"🇯🇵", "class":"emojiordered0261"},
{"emoji":":flag-kr:", "icon":"🇰🇷", "class":"emojiordered0272"},
{"emoji":":flag-kz:", "icon":"🇰🇿", "class":"emojiordered0268"},
{"emoji":":flag-lb:", "icon":"🇱🇧", "class":"emojiordered0283"},
{"emoji":":flag-mx:", "icon":"🇲🇽", "class":"emojiordered0299"},
{"emoji":":flag-my:", "icon":"🇲🇾", "class":"emojiordered0298"},
{"emoji":":flag-ng:", "icon":"🇳🇬", "class":"emojiordered0313"},
{"emoji":":flag-nl:", "icon":"🇳🇱", "class":"emojiordered0306"},
{"emoji":":flag-pe:", "icon":"🇵🇪", "class":"emojiordered0321"},
{"emoji":":flag-pt:", "icon":"🇵🇹", "class":"emojiordered0324"},
{"emoji":":flag-ru:", "icon":"🇷🇺", "class":"emojiordered0330"},
{"emoji":":flag-sa:", "icon":"🇸🇦", "class":"emojiordered0333"},
{"emoji":":flag-sg:", "icon":"🇸🇬", "class":"emojiordered0337"},
{"emoji":":flag-sy:", "icon":"🇸🇾", "class":"emojiordered0342"},
{"emoji":":flag-th:", "icon":"🇹🇭", "class":"emojiordered0362"},
{"emoji":":flag-tr:", "icon":"🇹🇷", "class":"emojiordered0357"},
{"emoji":":flag-tw:", "icon":"🇹🇼", "class":"emojiordered1364"},
{"emoji":":flag-ua:", "icon":"🇺🇦", "class":"emojiordered0368"},
{"emoji":":flag-us:", "icon":"🇺🇸", "class":"emojiordered0364"},
{"emoji":":flag-uy:", "icon":"🇺🇾", "class":"emojiordered0366"},
{"emoji":":flag-ve:", "icon":"🇻🇪", "class":"emojiordered0372"},
{"emoji":":flag-za:", "icon":"🇿🇦", "class":"emojiordered0377"},
{"emoji":":flags:", "icon":"🎏", "class":"emojiordered0524"},
{"emoji":":flashlight:", "icon":"🔦", "class":"emojiordered1094"},
{"emoji":":floppy_disk:", "icon":"💾", "class":"emojiordered0994"},
{"emoji":":flower_playing_cards:", "icon":"🎴", "class":"emojiordered0549"},
{"emoji":":flushed:", "icon":"😳", "class":"emojiordered1204"},
{"emoji":":foggy:", "icon":"🌁", "class":"emojiordered0396"},
{"emoji":":football:", "icon":"🏈", "class":"emojiordered0583"},
{"emoji":":fork_and_knife:", "icon":"🍴", "class":"emojiordered0495"},
{"emoji":":fountain:", "icon":"⛲", "class":"emojiordered0087"},
{"emoji":":four:", "icon":"4⃣", "class":"emojiordered0006"},
{"emoji":":four_leaf_clover:", "icon":"🍀", "class":"emojiordered0443"},
{"emoji":":fr:", "icon":"🇫🇷", "class":"emojiordered0228"},
{"emoji":":free:", "icon":"🆓", "class":"emojiordered0158"},
{"emoji":":fried_shrimp:", "icon":"🍤", "class":"emojiordered0479"},
{"emoji":":fries:", "icon":"🍟", "class":"emojiordered0474"},
{"emoji":":frog:", "icon":"🐸", "class":"emojiordered0669"},
{"emoji":":frowning:", "icon":"😦", "class":"emojiordered1191"},
{"emoji":":fuelpump:", "icon":"⛽", "class":"emojiordered0091"},
{"emoji":":full_moon:", "icon":"🌕", "class":"emojiordered0416"},
{"emoji":":full_moon_with_face:", "icon":"🌝", "class":"emojiordered0424"},
{"emoji":":game_die:", "icon":"🎲", "class":"emojiordered0547"},
{"emoji":":gb:", "icon":"🇬🇧", "class":"emojiordered0246"},
{"emoji":":gem:", "icon":"💎", "class":"emojiordered0937"},
{"emoji":":gemini:", "icon":"♊", "class":"emojiordered0058"},
{"emoji":":ghost:", "icon":"👻", "class":"emojiordered0883"},
{"emoji":":gift:", "icon":"🎁", "class":"emojiordered0505"},
{"emoji":":gift_heart:", "icon":"💝", "class":"emojiordered0956"},
{"emoji":":globe_with_meridians:", "icon":"🌐", "class":"emojiordered0411"},
{"emoji":":goat:", "icon":"🐐", "class":"emojiordered0629"},
{"emoji":":golf:", "icon":"⛳", "class":"emojiordered0088"},
{"emoji":":grapes:", "icon":"🍇", "class":"emojiordered0450"},
{"emoji":":green_apple:", "icon":"🍏", "class":"emojiordered0458"},
{"emoji":":green_book:", "icon":"📗", "class":"emojiordered1019"},
{"emoji":":green_heart:", "icon":"💚", "class":"emojiordered0953"},
{"emoji":":grey_exclamation:", "icon":"❕", "class":"emojiordered0127"},
{"emoji":":grey_question:", "icon":"❔", "class":"emojiordered0126"},
{"emoji":":grimacing:", "icon":"😬", "class":"emojiordered1197"},
{"emoji":":grin:", "icon":"😁", "class":"emojiordered1154"},
{"emoji":":grinning:", "icon":"😀", "class":"emojiordered1153"},
{"emoji":":guitar:", "icon":"🎻", "class":"emojiordered0556"},
{"emoji":":gun:", "icon":"🔫", "class":"emojiordered1099"},
{"emoji":":hamburger:", "icon":"🍔", "class":"emojiordered0463"},
{"emoji":":hammer:", "icon":"🔨", "class":"emojiordered1096"},
{"emoji":":hamster:", "icon":"🐹", "class":"emojiordered0670"},
{"emoji":":handbag:", "icon":"👜", "class":"emojiordered0768"},
{"emoji":":hankey:", "icon":"💩", "class":"emojiordered0968"},
{"emoji":":hash:", "icon":"#⃣", "class":"emojiordered0001"},
{"emoji":":hatched_chick:", "icon":"🐥", "class":"emojiordered0650"},
{"emoji":":hatching_chick:", "icon":"🐣", "class":"emojiordered0648"},
{"emoji":":headphones:", "icon":"🎧", "class":"emojiordered0536"},
{"emoji":":hear_no_evil:", "icon":"🙉", "class":"emojiordered1237"},
{"emoji":":heart:", "icon":"❤", "class":"emojiordered0129"},
{"emoji":":heart_decoration:", "icon":"💟", "class":"emojiordered0958"},
{"emoji":":heart_eyes:", "icon":"😍", "class":"emojiordered1166"},
{"emoji":":heart_eyes_cat:", "icon":"😻", "class":"emojiordered1212"},
{"emoji":":heartbeat:", "icon":"💓", "class":"emojiordered0946"},
{"emoji":":heartpulse:", "icon":"💗", "class":"emojiordered0950"},
{"emoji":":hearts:", "icon":"♥", "class":"emojiordered0070"},
{"emoji":":heavy_check_mark:", "icon":"✔", "class":"emojiordered0116"},
{"emoji":":heavy_division_sign:", "icon":"➗", "class":"emojiordered0132"},
{"emoji":":heavy_dollar_sign:", "icon":"💲", "class":"emojiordered0982"},
{"emoji":":heavy_minus_sign:", "icon":"➖", "class":"emojiordered0131"},
{"emoji":":heavy_multiplication_x:", "icon":"✖", "class":"emojiordered0117"},
{"emoji":":heavy_plus_sign:", "icon":"➕", "class":"emojiordered0130"},
{"emoji":":helicopter:", "icon":"🚁", "class":"emojiordered1270"},
{"emoji":":herb:", "icon":"🌿", "class":"emojiordered0442"},
{"emoji":":hibiscus:", "icon":"🌺", "class":"emojiordered0437"},
{"emoji":":high_brightness:", "icon":"🔆", "class":"emojiordered1062"},
{"emoji":":high_heel:", "icon":"👠", "class":"emojiordered0772"},
{"emoji":":hocho:", "icon":"🔪", "class":"emojiordered1098"},
{"emoji":":honey_pot:", "icon":"🍯", "class":"emojiordered0490"},
{"emoji":":honeybee:", "icon":"🐝", "class":"emojiordered0642"},
{"emoji":":horse:", "icon":"🐴", "class":"emojiordered0665"},
{"emoji":":hospital:", "icon":"🏥", "class":"emojiordered0596"},
{"emoji":":hotel:", "icon":"🏨", "class":"emojiordered0599"},
{"emoji":":hotsprings:", "icon":"♨", "class":"emojiordered0072"},
{"emoji":":hourglass:", "icon":"⌛", "class":"emojiordered0027"},
{"emoji":":hourglass_flowing_sand:", "icon":"⏳", "class":"emojiordered0033"},
{"emoji":":house:", "icon":"🏠", "class":"emojiordered0591"},
{"emoji":":house_with_garden:", "icon":"🏡", "class":"emojiordered0592"},
{"emoji":":hushed:", "icon":"😯", "class":"emojiordered1200"},
{"emoji":":ice_cream:", "icon":"🍨", "class":"emojiordered0483"},
{"emoji":":icecream:", "icon":"🍦", "class":"emojiordered0481"},
{"emoji":":id:", "icon":"🆔", "class":"emojiordered0159"},
{"emoji":":ideograph_advantage:", "icon":"🉐", "class":"emojiordered0393"},
{"emoji":":imp:", "icon":"👿", "class":"emojiordered0892"},
{"emoji":":inbox_tray:", "icon":"📥", "class":"emojiordered1033"},
{"emoji":":incoming_envelope:", "icon":"📩", "class":"emojiordered1037"},
{"emoji":":information_source:", "icon":"ℹ", "class":"emojiordered0017"},
{"emoji":":innocent:", "icon":"😇", "class":"emojiordered1160"},
{"emoji":":iphone:", "icon":"📱", "class":"emojiordered1045"},
{"emoji":":it:", "icon":"🇮🇹", "class":"emojiordered0258"},
{"emoji":":izakaya_lantern:", "icon":"🏮", "class":"emojiordered0605"},
{"emoji":":jack_o_lantern:", "icon":"🎃", "class":"emojiordered0507"},
{"emoji":":japan:", "icon":"🗾", "class":"emojiordered1151"},
{"emoji":":japanese_castle:", "icon":"🏯", "class":"emojiordered0606"},
{"emoji":":japanese_goblin:", "icon":"👺", "class":"emojiordered0882"},
{"emoji":":japanese_ogre:", "icon":"👹", "class":"emojiordered0881"},
{"emoji":":jeans:", "icon":"👖", "class":"emojiordered0762"},
{"emoji":":joy:", "icon":"😂", "class":"emojiordered1155"},
{"emoji":":joy_cat:", "icon":"😹", "class":"emojiordered1210"},
{"emoji":":jp:", "icon":"🇯🇵", "class":"emojiordered0261"},
{"emoji":":key:", "icon":"🔑", "class":"emojiordered1073"},
{"emoji":":keycap_ten:", "icon":"🔟", "class":"emojiordered1087"},
{"emoji":":kimono:", "icon":"👘", "class":"emojiordered0764"},
{"emoji":":kiss:", "icon":"💋", "class":"emojiordered0934"},
{"emoji":":kissing:", "icon":"😗", "class":"emojiordered1176"},
{"emoji":":kissing_cat:", "icon":"😽", "class":"emojiordered1214"},
{"emoji":":kissing_closed_eyes:", "icon":"😚", "class":"emojiordered1179"},
{"emoji":":kissing_heart:", "icon":"😘", "class":"emojiordered1177"},
{"emoji":":kissing_smiling_eyes:", "icon":"😙", "class":"emojiordered1178"},
{"emoji":":koala:", "icon":"🐨", "class":"emojiordered0653"},
{"emoji":":koko:", "icon":"🈁", "class":"emojiordered0380"},
{"emoji":":kr:", "icon":"🇰🇷", "class":"emojiordered0272"},
{"emoji":":large_blue_circle:", "icon":"🔵", "class":"emojiordered1109"},
{"emoji":":large_blue_diamond:", "icon":"🔷", "class":"emojiordered1111"},
{"emoji":":large_orange_diamond:", "icon":"🔶", "class":"emojiordered1110"},
{"emoji":":last_quarter_moon:", "icon":"🌗", "class":"emojiordered0418"},
{"emoji":":last_quarter_moon_with_face:", "icon":"🌜", "class":"emojiordered0423"},
{"emoji":":laughing:", "icon":"😆", "class":"emojiordered1159"},
{"emoji":":leaves:", "icon":"🍃", "class":"emojiordered0446"},
{"emoji":":ledger:", "icon":"📒", "class":"emojiordered1014"},
{"emoji":":left_luggage:", "icon":"🛅", "class":"emojiordered1363"},
{"emoji":":left_right_arrow:", "icon":"↔", "class":"emojiordered0018"},
{"emoji":":leftwards_arrow_with_hook:", "icon":"↩", "class":"emojiordered0024"},
{"emoji":":lemon:", "icon":"🍋", "class":"emojiordered0454"},
{"emoji":":leo:", "icon":"♌", "class":"emojiordered0060"},
{"emoji":":leopard:", "icon":"🐆", "class":"emojiordered0619"},
{"emoji":":libra:", "icon":"♎", "class":"emojiordered0062"},
{"emoji":":light_rail:", "icon":"🚈", "class":"emojiordered1277"},
{"emoji":":link:", "icon":"🔗", "class":"emojiordered1079"},
{"emoji":":lips:", "icon":"👄", "class":"emojiordered0689"},
{"emoji":":lipstick:", "icon":"💄", "class":"emojiordered0912"},
{"emoji":":lock:", "icon":"🔒", "class":"emojiordered1074"},
{"emoji":":lock_with_ink_pen:", "icon":"🔏", "class":"emojiordered1071"},
{"emoji":":lollipop:", "icon":"🍭", "class":"emojiordered0488"},
{"emoji":":loop:", "icon":"➿", "class":"emojiordered0135"},
{"emoji":":loudspeaker:", "icon":"📢", "class":"emojiordered1030"},
{"emoji":":love_hotel:", "icon":"🏩", "class":"emojiordered0600"},
{"emoji":":love_letter:", "icon":"💌", "class":"emojiordered0935"},
{"emoji":":low_brightness:", "icon":"🔅", "class":"emojiordered1061"},
{"emoji":":m:", "icon":"Ⓜ", "class":"emojiordered0034"},
{"emoji":":mag:", "icon":"🔍", "class":"emojiordered1069"},
{"emoji":":mag_right:", "icon":"🔎", "class":"emojiordered1070"},
{"emoji":":mahjong:", "icon":"🀄", "class":"emojiordered0149"},
{"emoji":":mailbox:", "icon":"📫", "class":"emojiordered1039"},
{"emoji":":mailbox_closed:", "icon":"📪", "class":"emojiordered1038"},
{"emoji":":mailbox_with_mail:", "icon":"📬", "class":"emojiordered1040"},
{"emoji":":mailbox_with_no_mail:", "icon":"📭", "class":"emojiordered1041"},
{"emoji":":mans_shoe:", "icon":"👞", "class":"emojiordered0770"},
{"emoji":":maple_leaf:", "icon":"🍁", "class":"emojiordered0444"},
{"emoji":":mask:", "icon":"😷", "class":"emojiordered1208"},
{"emoji":":meat_on_bone:", "icon":"🍖", "class":"emojiordered0465"},
{"emoji":":mega:", "icon":"📣", "class":"emojiordered1031"},
{"emoji":":melon:", "icon":"🍈", "class":"emojiordered0451"},
{"emoji":":memo:", "icon":"📝", "class":"emojiordered1025"},
{"emoji":":mens:", "icon":"🚹", "class":"emojiordered1346"},
{"emoji":":microphone:", "icon":"🎤", "class":"emojiordered0533"},
{"emoji":":microscope:", "icon":"🔬", "class":"emojiordered1100"},
{"emoji":":milky_way:", "icon":"🌌", "class":"emojiordered0407"},
{"emoji":":minibus:", "icon":"🚐", "class":"emojiordered1285"},
{"emoji":":minidisc:", "icon":"💽", "class":"emojiordered0993"},
{"emoji":":mobile_phone_off:", "icon":"📴", "class":"emojiordered1048"},
{"emoji":":money_with_wings:", "icon":"💸", "class":"emojiordered0988"},
{"emoji":":moneybag:", "icon":"💰", "class":"emojiordered0980"},
{"emoji":":monkey:", "icon":"🐒", "class":"emojiordered0631"},
{"emoji":":monkey_face:", "icon":"🐵", "class":"emojiordered0666"},
{"emoji":":monorail:", "icon":"🚝", "class":"emojiordered1298"},
{"emoji":":mortar_board:", "icon":"🎓", "class":"emojiordered0528"},
{"emoji":":mount_fuji:", "icon":"🗻", "class":"emojiordered1148"},
{"emoji":":mountain_cableway:", "icon":"🚠", "class":"emojiordered1301"},
{"emoji":":mountain_railway:", "icon":"🚞", "class":"emojiordered1299"},
{"emoji":":mouse2:", "icon":"🐁", "class":"emojiordered0614"},
{"emoji":":mouse:", "icon":"🐭", "class":"emojiordered0658"},
{"emoji":":movie_camera:", "icon":"🎥", "class":"emojiordered0534"},
{"emoji":":moyai:", "icon":"🗿", "class":"emojiordered1152"},
{"emoji":":mushroom:", "icon":"🍄", "class":"emojiordered0447"},
{"emoji":":musical_keyboard:", "icon":"🎹", "class":"emojiordered0554"},
{"emoji":":musical_note:", "icon":"🎵", "class":"emojiordered0550"},
{"emoji":":musical_score:", "icon":"🎼", "class":"emojiordered0557"},
{"emoji":":mute:", "icon":"🔇", "class":"emojiordered1063"},
{"emoji":":name_badge:", "icon":"📛", "class":"emojiordered1023"},
{"emoji":":necktie:", "icon":"👔", "class":"emojiordered0760"},
{"emoji":":negative_squared_cross_mark:", "icon":"❎", "class":"emojiordered0124"},
{"emoji":":neutral_face:", "icon":"😐", "class":"emojiordered1169"},
{"emoji":":new:", "icon":"🆕", "class":"emojiordered0160"},
{"emoji":":new_moon:", "icon":"🌑", "class":"emojiordered0412"},
{"emoji":":new_moon_with_face:", "icon":"🌚", "class":"emojiordered0421"},
{"emoji":":newspaper:", "icon":"📰", "class":"emojiordered1044"},
{"emoji":":ng:", "icon":"🆖", "class":"emojiordered0161"},
{"emoji":":nine:", "icon":"9⃣", "class":"emojiordered0011"},
{"emoji":":no_bell:", "icon":"🔕", "class":"emojiordered1077"},
{"emoji":":no_bicycles:", "icon":"🚳", "class":"emojiordered1325"},
{"emoji":":no_entry:", "icon":"⛔", "class":"emojiordered0085"},
{"emoji":":no_entry_sign:", "icon":"🚫", "class":"emojiordered1317"},
{"emoji":":no_mobile_phones:", "icon":"📵", "class":"emojiordered1049"},
{"emoji":":no_mouth:", "icon":"😶", "class":"emojiordered1207"},
{"emoji":":no_pedestrians:", "icon":"🚷", "class":"emojiordered1344"},
{"emoji":":no_smoking:", "icon":"🚭", "class":"emojiordered1319"},
{"emoji":":non-potable_water:", "icon":"🚱", "class":"emojiordered1323"},
{"emoji":":nose:", "icon":"👃", "class":"emojiordered1323"},
{"emoji":":notebook:", "icon":"📓", "class":"emojiordered1015"},
{"emoji":":notebook_with_decorative_cover:", "icon":"📔", "class":"emojiordered1016"},
{"emoji":":notes:", "icon":"🎶", "class":"emojiordered0551"},
{"emoji":":nut_and_bolt:", "icon":"🔩", "class":"emojiordered1097"},
{"emoji":":o2:", "icon":"🅾", "class":"emojiordered0153"},
{"emoji":":o:", "icon":"⭕", "class":"emojiordered0144"},
{"emoji":":ocean:", "icon":"🌊", "class":"emojiordered0405"},
{"emoji":":octopus:", "icon":"🐙", "class":"emojiordered0638"},
{"emoji":":oden:", "icon":"🍢", "class":"emojiordered0477"},
{"emoji":":office:", "icon":"🏢", "class":"emojiordered0593"},
{"emoji":":ok:", "icon":"🆗", "class":"emojiordered0162"},
{"emoji":":on:", "icon":"🔛", "class":"emojiordered1083"},
{"emoji":":oncoming_automobile:", "icon":"🚘", "class":"emojiordered1293"},
{"emoji":":oncoming_bus:", "icon":"🚍", "class":"emojiordered1282"},
{"emoji":":oncoming_police_car:", "icon":"🚔", "class":"emojiordered1289"},
{"emoji":":oncoming_taxi:", "icon":"🚖", "class":"emojiordered1291"},
{"emoji":":one:", "icon":"1⃣", "class":"emojiordered0003"},
{"emoji":":open_file_folder:", "icon":"📂", "class":"emojiordered0998"},
{"emoji":":open_mouth:", "icon":"😮", "class":"emojiordered1199"},
{"emoji":":ophiuchus:", "icon":"⛎", "class":"emojiordered0084"},
{"emoji":":orange_book:", "icon":"📙", "class":"emojiordered1021"},
{"emoji":":outbox_tray:", "icon":"📤", "class":"emojiordered1032"},
{"emoji":":ox:", "icon":"🐂", "class":"emojiordered0615"},
{"emoji":":package:", "icon":"📦", "class":"emojiordered1034"},
{"emoji":":page_facing_up:", "icon":"📄", "class":"emojiordered1000"},
{"emoji":":page_with_curl:", "icon":"📃", "class":"emojiordered0999"},
{"emoji":":pager:", "icon":"📟", "class":"emojiordered1027"},
{"emoji":":palm_tree:", "icon":"🌴", "class":"emojiordered0432"},
{"emoji":":panda_face:", "icon":"🐼", "class":"emojiordered0673"},
{"emoji":":paperclip:", "icon":"📎", "class":"emojiordered1010"},
{"emoji":":parking:", "icon":"🅿", "class":"emojiordered0154"},
{"emoji":":part_alternation_mark:", "icon":"〽", "class":"emojiordered0146"},
{"emoji":":partly_sunny:", "icon":"⛅", "class":"emojiordered0083"},
{"emoji":":passport_control:", "icon":"🛂", "class":"emojiordered1360"},
{"emoji":":paw_prints:", "icon":"🐾", "class":"emojiordered0675"},
{"emoji":":peach:", "icon":"🍑", "class":"emojiordered0460"},
{"emoji":":pear:", "icon":"🍐", "class":"emojiordered0459"},
{"emoji":":pencil2:", "icon":"✏", "class":"emojiordered0114"},
{"emoji":":pencil:", "icon":"📝", "class":"emojiordered1025"},
{"emoji":":penguin:", "icon":"🐧", "class":"emojiordered0652"},
{"emoji":":pensive:", "icon":"😔", "class":"emojiordered1173"},
{"emoji":":performing_arts:", "icon":"🎭", "class":"emojiordered0542"},
{"emoji":":persevere:", "icon":"😣", "class":"emojiordered1188"},
{"emoji":":phone:", "icon":"☎", "class":"emojiordered0045"},
{"emoji":":pig2:", "icon":"🐖", "class":"emojiordered0635"},
{"emoji":":pig:", "icon":"🐷", "class":"emojiordered0668"},
{"emoji":":pig_nose:", "icon":"🐽", "class":"emojiordered0674"},
{"emoji":":pill:", "icon":"💊", "class":"emojiordered0933"},
{"emoji":":pineapple:", "icon":"🍍", "class":"emojiordered0456"},
{"emoji":":pisces:", "icon":"♓", "class":"emojiordered0067"},
{"emoji":":pizza:", "icon":"🍕", "class":"emojiordered0464"},
{"emoji":":police_car:", "icon":"🚓", "class":"emojiordered1288"},
{"emoji":":poodle:", "icon":"🐩", "class":"emojiordered0654"},
{"emoji":":poop:", "icon":"💩", "class":"emojiordered0968"},
{"emoji":":post_office:", "icon":"🏣", "class":"emojiordered0594"},
{"emoji":":postal_horn:", "icon":"📯", "class":"emojiordered1043"},
{"emoji":":postbox:", "icon":"📮", "class":"emojiordered1042"},
{"emoji":":potable_water:", "icon":"🚰", "class":"emojiordered1322"},
{"emoji":":pouch:", "icon":"👝", "class":"emojiordered0769"},
{"emoji":":poultry_leg:", "icon":"🍗", "class":"emojiordered0466"},
{"emoji":":pound:", "icon":"💷", "class":"emojiordered0987"},
{"emoji":":pouting_cat:", "icon":"😾", "class":"emojiordered1215"},
{"emoji":":purple_heart:", "icon":"💜", "class":"emojiordered0955"},
{"emoji":":purse:", "icon":"👛", "class":"emojiordered0767"},
{"emoji":":pushpin:", "icon":"📌", "class":"emojiordered1008"},
{"emoji":":put_litter_in_its_place:", "icon":"🚮", "class":"emojiordered1320"},
{"emoji":":question:", "icon":"❓", "class":"emojiordered0125"},
{"emoji":":rabbit2:", "icon":"🐇", "class":"emojiordered0620"},
{"emoji":":rabbit:", "icon":"🐰", "class":"emojiordered0661"},
{"emoji":":racehorse:", "icon":"🐎", "class":"emojiordered0627"},
{"emoji":":radio:", "icon":"📻", "class":"emojiordered1054"},
{"emoji":":radio_button:", "icon":"🔘", "class":"emojiordered1080"},
{"emoji":":rage:", "icon":"😡", "class":"emojiordered1186"},
{"emoji":":railway_car:", "icon":"🚃", "class":"emojiordered1272"},
{"emoji":":rainbow:", "icon":"🌈", "class":"emojiordered0403"},
{"emoji":":ram:", "icon":"🐏", "class":"emojiordered0628"},
{"emoji":":ramen:", "icon":"🍜", "class":"emojiordered0471"},
{"emoji":":rat:", "icon":"🐀", "class":"emojiordered0613"},
{"emoji":":recycle:", "icon":"♻", "class":"emojiordered0073"},
{"emoji":":red_book:", "icon":"📕", "class":"emojiordered1017"},
{"emoji":":red_car:", "icon":"🚗", "class":"emojiordered1292"},
{"emoji":":red_circle:", "icon":"🔴", "class":"emojiordered1108"},
{"emoji":":registered:", "icon":"®", "class":"emojiordered0013"},
{"emoji":":relaxed:", "icon":"☺", "class":"emojiordered0055"},
{"emoji":":relieved:", "icon":"😌", "class":"emojiordered1165"},
{"emoji":":repeat:", "icon":"🔁", "class":"emojiordered1057"},
{"emoji":":repeat_one:", "icon":"🔂", "class":"emojiordered1058"},
{"emoji":":restroom:", "icon":"🚻", "class":"emojiordered1348"},
{"emoji":":revolving_hearts:", "icon":"💞", "class":"emojiordered0957"},
{"emoji":":rewind:", "icon":"⏪", "class":"emojiordered0029"},
{"emoji":":ribbon:", "icon":"🎀", "class":"emojiordered0504"},
{"emoji":":rice:", "icon":"🍚", "class":"emojiordered0469"},
{"emoji":":rice_ball:", "icon":"🍙", "class":"emojiordered0468"},
{"emoji":":rice_cracker:", "icon":"🍘", "class":"emojiordered0467"},
{"emoji":":rice_scene:", "icon":"🎑", "class":"emojiordered0526"},
{"emoji":":ring:", "icon":"💍", "class":"emojiordered0936"},
{"emoji":":rocket:", "icon":"🚀", "class":"emojiordered1269"},
{"emoji":":roller_coaster:", "icon":"🎢", "class":"emojiordered0531"},
{"emoji":":rooster:", "icon":"🐓", "class":"emojiordered0632"},
{"emoji":":rose:", "icon":"🌹", "class":"emojiordered0436"},
{"emoji":":rotating_light:", "icon":"🚨", "class":"emojiordered1314"},
{"emoji":":round_pushpin:", "icon":"📍", "class":"emojiordered1009"},
{"emoji":":ru:", "icon":"🇷🇺", "class":"emojiordered0330"},
{"emoji":":rugby_football:", "icon":"🏉", "class":"emojiordered0584"},
{"emoji":":running_shirt_with_sash:", "icon":"🎽", "class":"emojiordered0558"},
{"emoji":":sa:", "icon":"🈂", "class":"emojiordered0381"},
{"emoji":":sagittarius:", "icon":"♐", "class":"emojiordered0064"},
{"emoji":":sake:", "icon":"🍶", "class":"emojiordered0497"},
{"emoji":":sandal:", "icon":"👡", "class":"emojiordered0773"},
{"emoji":":satellite:", "icon":"📡", "class":"emojiordered1029"},
{"emoji":":saxophone:", "icon":"🎷", "class":"emojiordered0552"},
{"emoji":":school:", "icon":"🏫", "class":"emojiordered0602"},
{"emoji":":school_satchel:", "icon":"🎒", "class":"emojiordered0527"},
{"emoji":":scissors:", "icon":"✂", "class":"emojiordered0092"},
{"emoji":":scorpius:", "icon":"♏", "class":"emojiordered0063"},
{"emoji":":scream:", "icon":"😱", "class":"emojiordered1202"},
{"emoji":":scream_cat:", "icon":"🙀", "class":"emojiordered1217"},
{"emoji":":scroll:", "icon":"📜", "class":"emojiordered1024"},
{"emoji":":seat:", "icon":"💺", "class":"emojiordered0990"},
{"emoji":":secret:", "icon":"㊙", "class":"emojiordered0148"},
{"emoji":":see_no_evil:", "icon":"🙈", "class":"emojiordered1236"},
{"emoji":":seedling:", "icon":"🌱", "class":"emojiordered0429"},
{"emoji":":seven:", "icon":"7⃣", "class":"emojiordered0009"},
{"emoji":":shaved_ice:", "icon":"🍧", "class":"emojiordered0482"},
{"emoji":":sheep:", "icon":"🐑", "class":"emojiordered0630"},
{"emoji":":shell:", "icon":"🐚", "class":"emojiordered0639"},
{"emoji":":ship:", "icon":"🚢", "class":"emojiordered1303"},
{"emoji":":shit:", "icon":"💩", "class":"emojiordered0968"},
{"emoji":":shoe:", "icon":"👟", "class":"emojiordered0771"},
{"emoji":":signal_strength:", "icon":"📶", "class":"emojiordered1050"},
{"emoji":":six:", "icon":"6⃣", "class":"emojiordered0008"},
{"emoji":":six_pointed_star:", "icon":"🔯", "class":"emojiordered1103"},
{"emoji":":ski:", "icon":"🎿", "class":"emojiordered0560"},
{"emoji":":skull:", "icon":"💀", "class":"emojiordered0893"},
{"emoji":":sleeping:", "icon":"😴", "class":"emojiordered1205"},
{"emoji":":sleepy:", "icon":"😪", "class":"emojiordered1195"},
{"emoji":":slot_machine:", "icon":"🎰", "class":"emojiordered0545"},
{"emoji":":small_blue_diamond:", "icon":"🔹", "class":"emojiordered1113"},
{"emoji":":small_orange_diamond:", "icon":"🔸", "class":"emojiordered1112"},
{"emoji":":small_red_triangle:", "icon":"🔺", "class":"emojiordered1114"},
{"emoji":":small_red_triangle_down:", "icon":"🔻", "class":"emojiordered1115"},
{"emoji":":smile:", "icon":"😄", "class":"emojiordered1157"},
{"emoji":":smile_cat:", "icon":"😸", "class":"emojiordered1209"},
{"emoji":":smiley:", "icon":"😃", "class":"emojiordered1156"},
{"emoji":":smiling_imp:", "icon":"😈", "class":"emojiordered1161"},
{"emoji":":smirk:", "icon":"😏", "class":"emojiordered1168"},
{"emoji":":smirk_cat:", "icon":"😼", "class":"emojiordered1213"},
{"emoji":":smoking:", "icon":"🚬", "class":"emojiordered1318"},
{"emoji":":snail:", "icon":"🐌", "class":"emojiordered0625"},
{"emoji":":snake:", "icon":"🐍", "class":"emojiordered0626"},
{"emoji":":snowboarder:", "icon":"🏂", "class":"emojiordered0563"},
{"emoji":":snowflake:", "icon":"❄", "class":"emojiordered0121"},
{"emoji":":snowman:", "icon":"⛄", "class":"emojiordered0082"},
{"emoji":":sob:", "icon":"😭", "class":"emojiordered1198"},
{"emoji":":soccer:", "icon":"⚽", "class":"emojiordered0080"},
{"emoji":":soon:", "icon":"🔜", "class":"emojiordered1084"},
{"emoji":":sos:", "icon":"🆘", "class":"emojiordered0163"},
{"emoji":":sound2:", "icon":"🔊", "class":"emojiordered1066"},
{"emoji":":sound:", "icon":"🔉", "class":"emojiordered1065"},
{"emoji":":space_invader:", "icon":"👾", "class":"emojiordered0891"},
{"emoji":":spades:", "icon":"♠", "class":"emojiordered0068"},
{"emoji":":spaghetti:", "icon":"🍝", "class":"emojiordered0472"},
{"emoji":":sparkle:", "icon":"❇", "class":"emojiordered0122"},
{"emoji":":sparkler:", "icon":"🎇", "class":"emojiordered0516"},
{"emoji":":sparkles:", "icon":"✨", "class":"emojiordered0118"},
{"emoji":":sparkling_heart:", "icon":"💖", "class":"emojiordered0949"},
{"emoji":":speak_no_evil:", "icon":"🙊", "class":"emojiordered1238"},
{"emoji":":speaker:", "icon":"🔈", "class":"emojiordered1064"},
{"emoji":":speech_balloon:", "icon":"💬", "class":"emojiordered0976"},
{"emoji":":speedboat:", "icon":"🚤", "class":"emojiordered1310"},
{"emoji":":star2:", "icon":"🌟", "class":"emojiordered0426"},
{"emoji":":star:", "icon":"⭐", "class":"emojiordered0143"},
{"emoji":":stars:", "icon":"🌠", "class":"emojiordered0427"},
{"emoji":":station:", "icon":"🚉", "class":"emojiordered1278"},
{"emoji":":statue_of_liberty:", "icon":"🗽", "class":"emojiordered1150"},
{"emoji":":steam_locomotive:", "icon":"🚂", "class":"emojiordered1271"},
{"emoji":":stew:", "icon":"🍲", "class":"emojiordered0493"},
{"emoji":":straight_ruler:", "icon":"📏", "class":"emojiordered1011"},
{"emoji":":strawberry:", "icon":"🍓", "class":"emojiordered0462"},
{"emoji":":stuck_out_tongue:", "icon":"😛", "class":"emojiordered1180"},
{"emoji":":stuck_out_tongue_closed_eyes:", "icon":"😝", "class":"emojiordered1182"},
{"emoji":":stuck_out_tongue_winking_eye:", "icon":"😜", "class":"emojiordered1181"},
{"emoji":":sun_with_face:", "icon":"🌞", "class":"emojiordered0425"},
{"emoji":":sunflower:", "icon":"🌻", "class":"emojiordered0438"},
{"emoji":":sunglasses:", "icon":"😎", "class":"emojiordered1167"},
{"emoji":":sunny:", "icon":"☀", "class":"emojiordered0043"},
{"emoji":":sunrise:", "icon":"🌅", "class":"emojiordered0400"},
{"emoji":":sunrise_over_mountains:", "icon":"🌄", "class":"emojiordered0399"},
{"emoji":":sushi:", "icon":"🍣", "class":"emojiordered0478"},
{"emoji":":suspension_railway:", "icon":"🚟", "class":"emojiordered1300"},
{"emoji":":sweat:", "icon":"😓", "class":"emojiordered1172"},
{"emoji":":sweat_drops:", "icon":"💦", "class":"emojiordered0965"},
{"emoji":":sweat_smile:", "icon":"😅", "class":"emojiordered1158"},
{"emoji":":sweet_potato:", "icon":"🍠", "class":"emojiordered0475"},
{"emoji":":symbols:", "icon":"🔣", "class":"emojiordered1091"},
{"emoji":":syringe:", "icon":"💉", "class":"emojiordered0932"},
{"emoji":":tada:", "icon":"🎉", "class":"emojiordered0518"},
{"emoji":":tanabata_tree:", "icon":"🎋", "class":"emojiordered0520"},
{"emoji":":tangerine:", "icon":"🍊", "class":"emojiordered0453"},
{"emoji":":taurus:", "icon":"♉", "class":"emojiordered0057"},
{"emoji":":taxi:", "icon":"🚕", "class":"emojiordered1290"},
{"emoji":":tea:", "icon":"🍵", "class":"emojiordered0496"},
{"emoji":":telephone:", "icon":"☎", "class":"emojiordered0045"},
{"emoji":":telephone_receiver:", "icon":"📞", "class":"emojiordered1026"},
{"emoji":":telescope:", "icon":"🔭", "class":"emojiordered1101"},
{"emoji":":tennis:", "icon":"🎾", "class":"emojiordered0559"},
{"emoji":":tent:", "icon":"⛺", "class":"emojiordered0090"},
{"emoji":":thought_balloon:", "icon":"💭", "class":"emojiordered0977"},
{"emoji":":three:", "icon":"3⃣", "class":"emojiordered0005"},
{"emoji":":ticket:", "icon":"🎫", "class":"emojiordered0540"},
{"emoji":":tiger2:", "icon":"🐅", "class":"emojiordered0618"},
{"emoji":":tiger:", "icon":"🐯", "class":"emojiordered0660"},
{"emoji":":tired_face:", "icon":"😫", "class":"emojiordered1196"},
{"emoji":":tm:", "icon":"™", "class":"emojiordered0016"},
{"emoji":":toilet:", "icon":"🚽", "class":"emojiordered1350"},
{"emoji":":tokyo_tower:", "icon":"🗼", "class":"emojiordered1149"},
{"emoji":":tomato:", "icon":"🍅", "class":"emojiordered0448"},
{"emoji":":top:", "icon":"🔝", "class":"emojiordered1085"},
{"emoji":":tractor:", "icon":"🚜", "class":"emojiordered1297"},
{"emoji":":traffic_light:", "icon":"🚥", "class":"emojiordered1311"},
{"emoji":":train:", "icon":"🚋", "class":"emojiordered1280"},
{"emoji":":train_in_tunnel:", "icon":"🚇", "class":"emojiordered1276"},
{"emoji":":tram:", "icon":"🚊", "class":"emojiordered1279"},
{"emoji":":triangular_flag_on_post:", "icon":"🚩", "class":"emojiordered1315"},
{"emoji":":triangular_ruler:", "icon":"📐", "class":"emojiordered1012"},
{"emoji":":trident:", "icon":"🔱", "class":"emojiordered1105"},
{"emoji":":triumph:", "icon":"😤", "class":"emojiordered1189"},
{"emoji":":trolleybus:", "icon":"🚎", "class":"emojiordered1283"},
{"emoji":":tropical_drink:", "icon":"🍹", "class":"emojiordered0500"},
{"emoji":":tropical_fish:", "icon":"🐠", "class":"emojiordered0645"},
{"emoji":":truck:", "icon":"🚚", "class":"emojiordered1295"},
{"emoji":":trumpet:", "icon":"🎺", "class":"emojiordered0555"},
{"emoji":":tshirt:", "icon":"👕", "class":"emojiordered0761"},
{"emoji":":tulip:", "icon":"🌷", "class":"emojiordered0434"},
{"emoji":":turtle:", "icon":"🐢", "class":"emojiordered0647"},
{"emoji":":tv:", "icon":"📺", "class":"emojiordered1053"},
{"emoji":":twisted_rightwards_arrows:", "icon":"🔀", "class":"emojiordered1056"},
{"emoji":":two:", "icon":"2⃣", "class":"emojiordered0004"},
{"emoji":":two_hearts:", "icon":"💕", "class":"emojiordered0948"},
{"emoji":":two_men_holding_hands:", "icon":"👬", "class":"emojiordered0818"},
{"emoji":":two_women_holding_hands:", "icon":"👭", "class":"emojiordered0819"},
{"emoji":":u5272:", "icon":"🈹", "class":"emojiordered0391"},
{"emoji":":u5408:", "icon":"🈴", "class":"emojiordered0386"},
{"emoji":":u55b6:", "icon":"🈺", "class":"emojiordered0392"},
{"emoji":":u6307:", "icon":"🈯", "class":"emojiordered0383"},
{"emoji":":u6708:", "icon":"🈷", "class":"emojiordered0389"},
{"emoji":":u6709:", "icon":"🈶", "class":"emojiordered0388"},
{"emoji":":u6e80:", "icon":"🈵", "class":"emojiordered0387"},
{"emoji":":u7121:", "icon":"🈚", "class":"emojiordered0382"},
{"emoji":":u7533:", "icon":"🈸", "class":"emojiordered0390"},
{"emoji":":u7981:", "icon":"🈲", "class":"emojiordered0384"},
{"emoji":":u7a7a:", "icon":"🈳", "class":"emojiordered0385"},
{"emoji":":uk:", "icon":"🇬🇧", "class":"emojiordered0246"},
{"emoji":":umbrella:", "icon":"☔", "class":"emojiordered0047"},
{"emoji":":unamused:", "icon":"😒", "class":"emojiordered1171"},
{"emoji":":underage:", "icon":"🔞", "class":"emojiordered1086"},
{"emoji":":unlock:", "icon":"🔓", "class":"emojiordered1075"},
{"emoji":":up:", "icon":"🆙", "class":"emojiordered0164"},
{"emoji":":us:", "icon":"🇺🇸", "class":"emojiordered0364"},
{"emoji":":vertical_traffic_light:", "icon":"🚦", "class":"emojiordered1312"},
{"emoji":":vhs:", "icon":"📼", "class":"emojiordered1055"},
{"emoji":":vibration_mode:", "icon":"📳", "class":"emojiordered1047"},
{"emoji":":video_camera:", "icon":"📹", "class":"emojiordered1052"},
{"emoji":":video_game:", "icon":"🎮", "class":"emojiordered0543"},
{"emoji":":violin:", "icon":"🎸", "class":"emojiordered0553"},
{"emoji":":virgo:", "icon":"♍", "class":"emojiordered0061"},
{"emoji":":volcano:", "icon":"🌋", "class":"emojiordered0406"},
{"emoji":":vs:", "icon":"🆚", "class":"emojiordered0165"},
{"emoji":":waning_crescent_moon:", "icon":"🌘", "class":"emojiordered0419"},
{"emoji":":waning_gibbous_moon:", "icon":"🌖", "class":"emojiordered0417"},
{"emoji":":warning:", "icon":"⚠", "class":"emojiordered0076"},
{"emoji":":watch:", "icon":"⌚", "class":"emojiordered0026"},
{"emoji":":water_buffalo:", "icon":"🐃", "class":"emojiordered0616"},
{"emoji":":watermelon:", "icon":"🍉", "class":"emojiordered0452"},
{"emoji":":wavy_dash:", "icon":"〰", "class":"emojiordered0145"},
{"emoji":":waxing_crescent_moon:", "icon":"🌒", "class":"emojiordered0413"},
{"emoji":":waxing_gibbous_moon:", "icon":"🌔", "class":"emojiordered0415"},
{"emoji":":wc:", "icon":"🚾", "class":"emojiordered1351"},
{"emoji":":weary:", "icon":"😩", "class":"emojiordered1194"},
{"emoji":":wedding:", "icon":"💒", "class":"emojiordered0945"},
{"emoji":":whale2:", "icon":"🐋", "class":"emojiordered0624"},
{"emoji":":whale:", "icon":"🐳", "class":"emojiordered0664"},
{"emoji":":wheelchair:", "icon":"♿", "class":"emojiordered0074"},
{"emoji":":white_check_mark:", "icon":"✅", "class":"emojiordered0093"},
{"emoji":":white_circle:", "icon":"⚪", "class":"emojiordered0078"},
{"emoji":":white_flower:", "icon":"💮", "class":"emojiordered0978"},
{"emoji":":white_large_square:", "icon":"⬜", "class":"emojiordered0142"},
{"emoji":":white_medium_small_square:", "icon":"◽", "class":"emojiordered0041"},
{"emoji":":white_medium_square:", "icon":"◻", "class":"emojiordered0039"},
{"emoji":":white_small_square:", "icon":"▫", "class":"emojiordered0036"},
{"emoji":":white_square_button:", "icon":"🔳", "class":"emojiordered1107"},
{"emoji":":wind_chime:", "icon":"🎐", "class":"emojiordered0525"},
{"emoji":":wine_glass:", "icon":"🍷", "class":"emojiordered0498"},
{"emoji":":wink:", "icon":"😉", "class":"emojiordered1162"},
{"emoji":":wolf:", "icon":"🐺", "class":"emojiordered0671"},
{"emoji":":womans_clothes:", "icon":"👚", "class":"emojiordered0766"},
{"emoji":":womans_hat:", "icon":"👒", "class":"emojiordered0758"},
{"emoji":":womens:", "icon":"🚺", "class":"emojiordered1347"},
{"emoji":":worried:", "icon":"😟", "class":"emojiordered1184"},
{"emoji":":wrench:", "icon":"🔧", "class":"emojiordered1095"},
{"emoji":":x:", "icon":"❌", "class":"emojiordered0123"},
{"emoji":":yellow_heart:", "icon":"💛", "class":"emojiordered0954"},
{"emoji":":yen:", "icon":"💴", "class":"emojiordered0984"},
{"emoji":":yum:", "icon":"😋", "class":"emojiordered1164"},
{"emoji":":zap:", "icon":"⚡", "class":"emojiordered0077"},
{"emoji":":zero:", "icon":"0⃣", "class":"emojiordered0002"},
{"emoji":":zzz:", "icon":"💤", "class":"emojiordered0963"}
]};

	var items = json.items;
	var autocomplete_init = false;
	var emojiIndex = 0;

	function doGetCaretPosition (element1)
	{
		var caretOffset = 0;
		var range = window.getSelection().getRangeAt(0);
		var preCaretRange = range.cloneRange();
		preCaretRange.selectNodeContents(element1);
		preCaretRange.setEnd(range.endContainer, range.endOffset);
		caretOffset = preCaretRange.toString().length;
		return caretOffset;
	}

//keyup function
	document.addEventListener("keyup", function (event) {
//$(document).keyup(function( event ) {
	var index = doGetCaretPosition(document.getElementsByClassName("input")[1]);
	var guncelString = document.getElementsByClassName("input")[1].innerText;
	var emoji_string = guncelString.substring(0, index);
	var emoji_start_pos = emoji_string.lastIndexOf(":");
	var emoji_filter = guncelString.substring(emoji_start_pos,index);
	var keycode = event.keyCode;

if(guncelString.indexOf(':') > -1 && event.keyCode!=16 && event.keyCode!=38 && event.keyCode!=39 && event.keyCode!=37 && event.keyCode!=40 && event.keyCode != 13){ //except enter keycode
	filter_emojis(emoji_filter,event);
}
if (guncelString.indexOf(':') == -1 ){
	document.getElementsByClassName("autocomplete_main")[0].innerHTML = "";
}
if (keycode == 27){
	document.getElementsByClassName("autocomplete_main")[0].innerHTML = "";
}
if(document.getElementsByClassName("emoji-shortcut")[0] != undefined && document.getElementsByClassName("autocomplete_main")[0].innerText != ""){
	document.getElementsByClassName("input")[1].addEventListener("keydown", function(e) {
		if([37, 38, 39, 40, 13].indexOf(e.keyCode) > -1 && document.getElementsByClassName("autocomplete_main")[0].innerText != "") {
			e.preventDefault();
			if(e.preventDefault){
            e.preventDefault();
        }
         if (e.stopPropagation) {
            e.stopPropagation();
         }
        
			if(e.keyCode == 13){
				index = doGetCaretPosition(document.getElementsByClassName("input")[1]);
				guncelString = document.getElementsByClassName("input")[1].innerText;
				emoji_string = guncelString.substring(0, index);
				emoji_start_pos = emoji_string.lastIndexOf(":");
				emoji_filter = guncelString.substring(emoji_start_pos,index);
				var emojiUTF = document.getElementsByClassName("autocomplete_main")[0].getElementsByClassName("emoji")[emojiIndex].innerText;
				guncelString = guncelString.replace(emoji_filter, emojiUTF);
				//window.alert(guncelString);
				//document.getElementsByClassName("input")[1].innerText = guncelString;
				//window.alert(guncelString);
				emojiIndex = 0;
				document.getElementsByClassName("autocomplete_main")[0].innerHTML = "";
				document.getElementsByClassName("autocomplete_main")[0].style.padding = "0px";
				console.log(guncelString);
				document.getElementsByClassName("input")[1].innerText = "";
				document.execCommand('insertHtml', null, guncelString);
				//document.execCommand('insertHtml', null, "&nbsp;");
				//document.getElementsByClassName("pane-chat-tile-container")[0] = this.value.length;
				return false;
			}
		}
	}, false);
	switch(event.keyCode){
		case 38:
		event.preventDefault();
		nextItem(emojiIndex);
		break;
		case 39:
		event.preventDefault();
		nextItem(emojiIndex);
		break;
		case 40:
		event.preventDefault();
		previousItem(emojiIndex);
		break;
		case 37:
		event.preventDefault();
		previousItem(emojiIndex);
		break;

	}

}
return false;
});

//creating autocomplete div
function create_autocomplete()
{
	if(!autocomplete_init || document.getElementsByClassName("autocomplete_main")[0] == undefined){
		var parent_div = document.getElementsByClassName("pane-chat-tile-container")[0];
		var autocomplete_div = document.createElement("div");

		autocomplete_div.classList.add('autocomplete_main');

		parent_div.parentNode.insertBefore(autocomplete_div, parent_div.nextSibling);
		autocomplete_div.style.textAlign = "center";
		autocomplete_div.style.overflow = 'hidden';
		autocomplete_div.style.color = '#009688';
		autocomplete_div.style.backgroundColor = '#f3f0ef';
		autocomplete_div.style.padding = '10px';
		autocomplete_div.style.width = '100%';
		autocomplete_init = true;



	}
}

//filtering emojis
function filter_emojis(filtered_string, event)
{
	var size = 0;
	var emoji_string = "";
	create_autocomplete();
	var emojis = document.getElementsByClassName("autocomplete_main")[0];
	emojis.innerHTML = '';
	for(var i = 0; i < items.length; i++)
	{
		if(items[i].emoji.indexOf(filtered_string) > -1){
			var div = document.createElement("div");
			div.classList.add("emoji-shortcut");
			var h5 = document.createElement("h5");
			h5.innerHTML = items[i].emoji;
			div.appendChild(h5);
			var p = document.createElement("p");
			var innerp = document.createElement("i");
			emoji_string = items[i].emoji;
			emoji_string = emoji_string.replace(":","");
			emoji_string = emoji_string.replace(":","");
			emoji_string = "em-" + emoji_string;
			//innerp.classList.add("emojiutf");
			innerp.classList.add("em");
			innerp.classList.add(emoji_string);
			innerp.style.color = "transparent";
			innerp.contentEditable = false;
			p.appendChild(innerp);
			innerp.innerHTML = items[i].icon;
			p.classList.add("emoji");
			//p.classList.add(items[i].class);
			p.style.backgroundImage = "none";
			div.appendChild(p);
			emojis.appendChild(div);
			div.style.float = "left";
			div.style.padding = "5px";
			p.style.color = "black";
			size++;
			if(size>40)
				break;
		}
	}
	highlightItem(0);
}

function nextItem(activeIndex){
	var activeShortucts = document.getElementsByClassName("emoji-shortcut");
	var activeCount = activeShortucts.length;
	if(activeIndex + 1 >= activeCount){
		highlightItem(0);
		emojiIndex = 0;}
		else {
			highlightItem(activeIndex + 1);
			emojiIndex++;
		}
	}

	function previousItem(activeIndex){
		var activeShortucts = document.getElementsByClassName("emoji-shortcut");
		var activeCount = activeShortucts.length;
		if(activeIndex == 0){
			highlightItem(activeCount - 1);
			emojiIndex = activeCount - 1;}
			else {
				highlightItem(activeIndex - 1);
				emojiIndex--;
			}
		}

		function highlightItem(emoIndex){
			var itemtobeHighlighted = document.getElementsByClassName("emoji-shortcut")[emoIndex];
			var dehighlighList = document.getElementsByClassName("emoji-shortcut");
			for(var i = 0; i < dehighlighList.length; i++){
				document.getElementsByClassName("emoji-shortcut")[i].style.backgroundColor = 'transparent';
			}
			itemtobeHighlighted.style.backgroundColor = '#ccc';
			itemtobeHighlighted.style.borderRadius = "10px";
		}
})();